[project]
name = "aws-snowflake-dbt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dbt-core>=1.11.2",
    "dbt-snowflake>=1.11.0",
]
